name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Show environment
        shell: pwsh
        run: |
          Get-ComputerInfo | Select-Object WindowsProductName, WindowsVersion
          dotnet --info

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: Restore
        shell: pwsh
        run: |
          msbuild "All In One.csproj" `
            /t:Restore `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:EnableWindowsTargeting=true
      
      - name: Build and Package MSIX
        shell: pwsh
        run: |
          msbuild "All In One.csproj" `
            /t:Publish `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:AppxBundle=Never `
            /p:AppxPackageSigningEnabled=false `
            /p:SelfContained=true `
            /p:GenerateAppxPackageOnBuild=true `
            /p:EnableWindowsTargeting=true

      - name: Find MSIX files
        run: Get-ChildItem -Path . -Filter *.msix -Recurse

      - name: Upload Unsigned MSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-msix-x64
          path: '**/*.msix'
          if-no-files-found: error
