name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore
        run: >
          msbuild "All In One.csproj"
          /t:Restore
          /p:Configuration=Release
          /p:Platform=x64

      - name: Build and Package MSIX
        run: >
          msbuild "All In One.csproj"
          /t:Publish
          /p:Configuration=Release
          /p:Platform=x64
          /p:AppxPackageDir="${{ runner.temp }}\AppxPackages\"
          /p:AppxBundle=Never
          /p:AppxPackageSigningEnabled=false
          /p:SelfContained=true

      - name: Find MSIX files
        run: Get-ChildItem -Path ${{ runner.temp }} -Filter *.msix -Recurse

      - name: Upload Unsigned MSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-msix-x64
          path: ${{ runner.temp }}/AppxPackages/**/*.msix
          if-no-files-found: error